apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
spec:
  volumes:
  - name: app-data
    emptyDir: {}
  initContainers: 
  - name: download
    image: alpine:3.22.2
    command: ['sh','-c','apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/lxk-Dec.git /app; echo "git repo downloaded"']
    volumeMounts:
    - name: app-data
      mountPath: /app
  - name: delay
    image: busybox
    command: ['sh', '-c', 'sleep 15']
  containers:
  - name: web
    image: nginx:1.19.2
    volumeMounts:
    - name: app-data
      mountPath: /usr/share/nginx/html
