apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600 ; done']
