apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
    app: web
    test: pod
  name: test-pod
spec:
  containers:
  - image: nginx
    name: test-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
