apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-podname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-podname
  template:
    metadata:
      labels:
        app: nginx-podname
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                cat > /usr/share/nginx/html/index.html <<EOF
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Pod Information</title>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            display: flex;
                            justify-content: center;
                            align-items: center;
                            height: 100vh;
                            margin: 0;
                            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        }
                        .container {
                            background: white;
                            padding: 40px;
                            border-radius: 10px;
                            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
                            text-align: center;
                        }
                        h1 { color: #333; margin-bottom: 20px; }
                        .pod-name { 
                            font-size: 24px; 
                            color: #667eea; 
                            font-weight: bold;
                            word-break: break-all;
                        }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>Running on Pod:</h1>
                        <div class="pod-name">$HOSTNAME</div>
                    </div>
                </body>
                </html>
                EOF
      volumes:
      - name: html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-podname-service
spec:
  selector:
    app: nginx-podname
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
