apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
  labels:
    project: workshop
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        project: workshop
    spec:
      containers:
        - name: echo
          image: busybox
          command: ["sh", "-c", "echo test; sleep 15"]
      restartPolicy: Never
