apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  containers:
  - name: web
    image: nginx
  tolerations:
  - key: maintenance
    operator: "Equal"
    value: "true" 
    effect: "NoSchedule"  
